[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world_anchor = "HdZDgSANZbYPc439ktrx4G4M6f58HVA4hnyUZD1kawnZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/capybara/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
